language: haskell
notifications:
  email:
    - cg.wowus.cg@gmail.com
  on_success: always
  on_failure: always
install:
    - cabal install --only-dependencies --enable-tests --enable-benchmarks
    - cabal configure --enable-tests --enable-benchmarks
    - cabal build
    - cabal test --show-details=always
    - cabal bench
